---
update: true
swapfile_path: /swapfile
swapfile_size: 8G


base_packages:
  - base
  - base-devel
  - linux
  - linux-firmware
  - sudo
  - dhcpcd
  - netctl
  - networkmanager
  - openssh
  - pipewire
  - man-db
  - man-pages
  - git
  - wget
  - reflector
  - curl

xorg_packages:
  - xorg
  - xorg-apps
  - xorg-drivers
  - xorg-fonts
  - xorg-xinit

i3_packages:
  - i3-wm
  - i3status
  - rofi # Program launcher.
  - sddm

tmuxinator:
  - tmuxinator

neovim:
  - neovim-nightly-bin
  - stylua
  - lua-language-server


other_packages:
  - stow
  - firefox
  - alacritty
  - tmux
  - xclip
  - ripgrep
  - htop
  - zsh-syntax-highlighting
  - zsh-autosuggestions
  - fzf

services_list:
  - sshd
  - NetworkManager
  - reflector

dev_packages:
  - python
  - python-pip
  - nodejs
  - rust
  - jdk
  - go
  - ty
  - ruff
  - uv
  - black
  - mdformat
  - taplo
  - vscode-json-languageserver
  - marksman
  - yaml-language-server
  - tree-sitter-cli
  - jq
  - ast-grep
  - fd
  - pyright

dev_uv_installed_packages:
  - isort
  - black

graphics_packages:
  - nvidia-470xx-dkms
  - bbswitch-dkms
