---
- name: Ensure zsh is installed
  become: true
  pacman:
    name: zsh
    state: present

- name: Ensure zsh is valid shell
  become: true
  lineinfile:
    path: /etc/shells
    line: /bin/zsh
    state: present

- name: Set default shell for user
  become: true
  user:
    name: oskarand
    shell: /bin/zsh
